### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [renatapro/zadanie12.3#1]
- [x] nie potrzebujesz zaciagac `jquery-ui`, wystarczy Ci samo jquery
- [x] przepusc html przez walidator
- [x] zmienna `countriesCapital` nie jest Ci do niczego potrzebna

**Comment by renatapro** [comment]
czy tą część dotyczącą napisania kodu w przypadku wystąpienia błędu mam teraz zrobić na zaliczenie czy mogę już zrobić to później:)

**Comment by zdolny** [comment]
nie wiem o jaki blad chodzi - dla mnie wszystko gra :)
